plugin = /usr/lib/libhy3.so
plugin {
  hy3 {
      # if tab backgrounds should be blurred
      # Blur is only visible when the above colors are not opaque.
      blur = true # default: true
    #
    #   # opacity multiplier for tabs
    #   # Applies to blur as well as the given colors.
    #   opacity = <float> # default: 1.0
    # }

    # autotiling settings
    autotile {
      # enable autotile
      enable = true # default: false

      # # make autotile-created groups ephemeral
      # ephemeral_groups = <bool> # default: true
      #
      # # if a window would be squished smaller than this width, a vertical split will be created
      # # -1 = never automatically split vertically
      # # 0 = always automatically split vertically
      # # <number> = pixel width to split at
      # trigger_width = <int> # default: 0
      #
      # # if a window would be squished smaller than this height, a horizontal split will be created
      # # -1 = never automatically split horizontally
      # # 0 = always automatically split horizontally
      # # <number> = pixel height to split at
      # trigger_height = <int> # default: 0
      #
      # # a space or comma separated list of workspace ids where autotile should be enabled
      # # it's possible to create an exception rule by prefixing the definition with "not:"
      # # workspaces = 1,2 # autotiling will only be enabled on workspaces 1 and 2
      # # workspaces = not:1,2 # autotiling will be enabled on all workspaces except 1 and 2
      # workspaces = <string> # default: all
    }
  }
}
