local map = vim.keymap.set
local dap = require('dap')
local ui = require('dapui')

map('n', '<leader>do', function()
    ui.open()
    dap.continue()
end)
map('n', '<leader>dc', function()
    dap.terminate()
    ui.close()
end)

map('n', '<F5>', function()
    dap.continue()
end)
map('n', '<F3>', function()
    dap.terminate()
end)
map('n', '<F4>', function()
    dap.restart()
end)
map('n', '<F6>', function()
    dap.pause()
end)
map('n', '<leader>b', function()
    dap.toggle_breakpoint()
end)
map('n', '<F10>', function()
    dap.step_over()
end)
map('n', '<F11>', function()
    dap.step_into()
end)
map('n', '<F12>', function()
    dap.step_out()
end)
