local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
vim.keymap.set('n', '<leader>fg', builtin.live_grep, {})
vim.keymap.set('n', '<leader>fb', builtin.buffers, {})
vim.keymap.set('n', '<leader>fh', builtin.help_tags, {})
vim.keymap.set('n', '<leader>fr', builtin.lsp_references, {})
vim.keymap.set('n', '<leader>ft', function()
    local cur_buf = vim.fn.bufnr('%')
    local file_name = vim.fn.bufname(cur_buf)
    local abs_path = vim.fn.expand(file_name)
    local cur_dir = vim.fn.fnamemodify(abs_path, ':h')
    vim.cmd('!ctags -R ' .. cur_dir)
    builtin.tags()
end, {})
