-- ############ Plugins options ##################--
require('lazynvim')
require('plugins.icons')
require('plugins.comment')
require('plugins.autopairs')
require('plugins.picker')
require('plugins.blankline')
require('plugins.bufferline')
require('plugins.lualine')
require('plugins.neotree')
require('plugins.mason')
require('plugins.lint')
require('plugins.lsp')
require('plugins.cmp')
require('plugins.formatter')
require('plugins.dap.adapters')
require('plugins.dap.ui')
require('plugins.tasks')
require('plugins.treesitter')
require('plugins.snippets')
require('plugins.windows')
require('plugins.hop')
require('plugins.cppassist')

-- ############# Basic options ###################--
require('base.core_opts')
require('base.keymaps')
