$terminal = kitty
$fileManager = yazi
$menu = rofi -show drun

# ##############################################
# ##                           _              ##
# ##  ___  ___  _   _ _ __ ___(_)_ __   __ _  ##
# ## / __|/ _ \| | | | '__/ __| | '_ \ / _` | ##
# ## \__ \ (_) | |_| | | | (__| | | | | (_| | ##
# ## |___/\___/ \__,_|_|  \___|_|_| |_|\__, | ##
# ##                                   |___/  ##
# ##############################################

source = ~/.config/hypr/settings/monitor.conf
source = ~/.config/hypr/settings/env_vars.conf
source = ~/.config/hypr/settings/layouts.conf
source = ~/.config/hypr/settings/background.conf
source = ~/.config/hypr/settings/status_bar.conf
source = ~/.config/hypr/settings/window_gaps.conf
source = ~/.config/hypr/settings/corners.conf
source = ~/.config/hypr/settings/blur_system.conf
source = ~/.config/hypr/settings/manual_settings.conf
source = ~/.config/hypr/settings/animations.conf/
source = ~/.config/hypr/settings/shadow_range.conf
source = ~/.config/hypr/settings/shadow_color.conf
source = ~/.config/hypr/settings/border_size.conf
source = ~/.config/hypr/settings/border_color_active.conf
source = ~/.config/hypr/settings/border_color_inactive.conf
source = ~/.config/hypr/settings/plugins.conf
